name: iTags
author: jacklink01
version: 2.0
main: com.jacklinkproductions.iTags.Main

commands:
   itags:
      description: Information about the plugin.
      usage: /<command> info
   ding:
      description: Send a note to a player.
      usage: /<command> [player] [pitch]
   trending:
      description: Trending hashtags on this server.
      usage: /<command>
   print:
      description: Print directly into chat.
      usage: /<command> [message]