name: iTags
author: jacklink01
version: 2.1.2
main: com.jacklinkproductions.iTags.Main

commands:
   itags:
      description: Information about the plugin.
      usage: /<command>
   itags reload:
      description: Reloads the config.
      usage: /<command> reload
   itags update:
      description: Updates to the latest version.
      usage: /<command> update
   ding:
      description: Send a note to a player.
      usage: /<command> [player] [pitch]
   trending:
      description: Trending hashtags on this server.
      usage: /<command>